name: Build Browser Bundle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_bundle:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build (prod)
      # Допустим, в package.json есть "scripts": { "build": "webpack --mode production" }
      run: npm run build

    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: browser-dist
        path: dist/
