name: Build WebGazer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_webgazer:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build (prod)
      run: npm run build

    - name: List build folder
      run: ls -R dist

    - name: Upload dist
      uses: actions/upload-artifact@v3
      with:
        name: webgazer-dist
        path: dist/
